version: '3.8'

services:
  express:
    container_name: express
    image: node:20.10.0
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run build"