name: deploy-backend
run-name: ${{ github.actor }} is deploying...
on: [push]

jobs:
  deploy-to-server:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: npm run build

      - name: Start server
        run: npm run start